# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('idbank', models.IntegerField(primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.BankModel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='idtran',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserModel'),
        ),
    ]
